# -*- coding: utf-8 -*-
"""Untitled9.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1bgb5gzmz5iQPIyDaPDO4w9wi8x7sMHbA
"""

# Commented out IPython magic to ensure Python compatibility.
import cv2
import numpy as np
import matplotlib.pyplot as plt
# %matplotlib inline

img_path = 'aulia.png'
img = cv2.imread(img_path)
print(img.shape)

fix_img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
plt.imshow(fix_img)

R, G, B = fix_img[:,:,0], fix_img[:,:,1], fix_img[:,:,2]
print(np.array(fix_img))

fix_img[:] = np.max(fix_img, axis = -1, keepdims = 1)/2 + np.min(fix_img, axis = -1, keepdims = 1)/2

print(np.array, fix_img[:])
plt.axis('off') ##menghilangkan garis
plt.imshow(fix_img[:])
plt.savefig('metode lightness.jpg') ##bbox_inches = 'tight' (garis putih)

gray_img = np.mean(fix_img, axis = 2)
print(np.array(gray_img))

plt.axis('off')
plt.imshow(gray_img, cmap = 'gray')
plt.savefig('Metode Average.jpg', bbox_inches = 'tight')

lumi_img = (0.2126*R) + (0.7152*G) + (0.0722*B)
print(lumi_img)

plt.axis('off')
plt.imshow(lumi_img,cmap ='gray')
plt.savefig('Metode Average.jpg', bbox_inches = 'tight')

wavr_img = (0.299*R) + (0.587*G) + (0.114*B)
print(wavr_img)

plt.axis('off')
plt.imshow(wavr_img,cmap ='gray')
plt.savefig('Metode Average.jpg', bbox_inches = 'tight')

"""# New section"""